### ISSUE TITLE
default clock type

### ISSUE THREAD

**Issue by kibaekkim** [coin-or/CHiPPS-ALPS#1]
The default clock type is CPU. The comment in the [header file](https://github.com/coin-or/CHiPPS-ALPS/blob/master/Alps/src/AlpsParams.h#L70) needs corrected.

**Comment by tkralphs** [comment]
OK, I will correct this. It's not clear we should even have a parameter for clock type. On Windows, you only really have wall clock time (at least this used to be the case) and on Linux and OS X, I guess you always want CPU time in sequential mode and wall clock in parallel mode (CPU time doesn't have a very nice interpretation there). Perhaps in a shared memory parallel mode, CPU time would make sense for a parallel code, but with MPI, it seems wall time is what one wants to know.

**Comment by kibaekkim** [comment]
Here is the [line](https://github.com/kibaekkim/CHiPPS-ALPS/blob/master/Alps/src/AlpsParams.cpp#L213) corrected in my fork. I can create a pull request for this issue also with #2.

**Comment by tkralphs** [comment]
Fixed by 4eb7d5ccd4684d3a98b26b95a038ee4c571345a0
